---
name: Fetch Articles and Generate Feed

on:
  push:
    paths:
      - "articles/**"
  schedule:
    # FIXME: Is the schedule good enough?
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    # Don't run generate on push
    if: ${{ github.event_name != 'push' }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Download latest rumen-cli binary
        run: |
          wget -c https://punchagan.github.io/rumen/scripts/rumen-cli.exe
          chmod a+x rumen-cli.exe

      - name: Generate Feed
        run: |
          ./rumen-cli.exe generate --id "feed:$GITHUB_REPOSITORY"
          mkdir web/
          mv atom.xml web/

      - name: Upload web/ to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

  fetch:
    runs-on: ubuntu-latest

    # Fetch only runs if the triggering event was a 'push' to 'main'
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Readability CLI
        run: |
          npm install -g readability-cli

      - name: Download latest rumen-cli binary
        run: |
          wget -c https://punchagan.github.io/rumen/scripts/rumen-cli.exe
          chmod a+x rumen-cli.exe

      - name: Fetch article contents
        run: |
          ./rumen-cli.exe fetch

      - name: Commit any newly fetched contents
        run: |
          git add articles/
          git config user.email "rumen.fetch@example.com"
          git config user.name "Rumen CLI Fetch"
          git commit -m "Fetched article content" || echo "No changes to commit"
          git push
